
# @name get-notifications
GET http://localhost:3333/notifications 

###

# @name new-appointment
POST http://localhost:3333/appointment
Content-Type: application/json

{
  "nameClient": "Nome do Cliente",
  "idUser": "ID do Usuário",
  "description": "Descrição do Agendamento"
}