
# @name get-notifications
GET http://localhost:3333/notifications 

###

# @name new-appointment
POST http://localhost:3333/appointment
Content-Type: application/json

{
  "nameClient": "Nome do Cliente",
  "idUser": "ID do Usuário",
  "description": "Descrição do Agendamento",
  "dateAppointment": "26/09/2023",
  "timeAppointment": "14:20",
  "doctorId": "1144da8c-d3ba-4ed0-a7ad-4062b1d05e5d"
}

###

# @name get-appointments
GET http://localhost:3333/appointment


###

# @name get-doctors
GET http://localhost:3333/doctors

###

# DELETE http://localhost:3333/appointment